Repository GitHarpon/git-harpon, pull requests merged in 2019-02, with the labels that each got.

#2 Ajout en.json et fr.json
  main.ts
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  yarn.lock
Labels: feature

#3 Création du composant button
  src/app/app.module.ts
  src/app/components/button/button.component.html
  src/app/components/button/button.component.scss
  src/app/components/button/button.component.spec.ts
  src/app/components/button/button.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.scss
  src/app/components/toolbox/toolbox.component.ts
  src/variables.scss
Labels: feature

#4 feat(input): Ajout des différents input text dans la toolbox
  src/app/app.module.ts
  src/app/components/input/input.component.html
  src/app/components/input/input.component.scss
  src/app/components/input/input.component.spec.ts
  src/app/components/input/input.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.scss
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.scss
  src/variables.scss
Labels: feature

#5 Devtool augury
  main.ts
Labels: feature

#6 refactor(button): Ajout traduction sur les boutons
  src/app/components/button/button.component.html
  src/app/components/button/button.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: refactor

#8 Refactor input toolbox
  src/app/components/toolbox/toolbox.component.html
Labels: refactor

#10 Création du composant menu contextuel
  package.json
  src/app/app.module.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.scss
  yarn.lock
Labels: feature

#9 feat(input-number): Création du composant input-number
  src/app/app.module.ts
  src/app/components/input-number/input-number.component.html
  src/app/components/input-number/input-number.component.scss
  src/app/components/input-number/input-number.component.spec.ts
  src/app/components/input-number/input-number.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
Labels: feature

#12 feat(checkbox): Ajout du composant checkbox
  src/app/app.module.ts
  src/app/components/checkbox/checkbox.component.html
  src/app/components/checkbox/checkbox.component.scss
  src/app/components/checkbox/checkbox.component.spec.ts
  src/app/components/checkbox/checkbox.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#13 fix(toolbox): Fix apres merge sur la develop
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
Labels: feature

#14 feat(iconbutton): ajout du composant iconbutton
  src/app/app.module.ts
  src/app/components/icon-button/icon-button.component.html
  src/app/components/icon-button/icon-button.component.scss
  src/app/components/icon-button/icon-button.component.spec.ts
  src/app/components/icon-button/icon-button.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#15 fix(toolbox): fix après PR + conflit
  src/app/components/toolbox/toolbox.component.html
Labels: fix

#11 feat(dropdown) Ajout de la feature dropdown.
  src/app/app.module.ts
  src/app/components/dropdown/dropdown.component.html
  src/app/components/dropdown/dropdown.component.scss
  src/app/components/dropdown/dropdown.component.spec.ts
  src/app/components/dropdown/dropdown.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#20 fix(context-menu): faute d'orthographe
  src/app/components/toolbox/toolbox.component.html
Labels: fix

#16 feat(modal): Création du composant modal
  package.json
  src/app/app.module.ts
  src/app/components/input-number/input-number.component.ts
  src/app/components/modal/modal.component.html
  src/app/components/modal/modal.component.scss
  src/app/components/modal/modal.component.spec.ts
  src/app/components/modal/modal.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.scss
  yarn.lock
Labels: feature

#23 test(initial): Ajout des tests pour travis
  .travis.yml
  README.md
  package.json
  src/app/components/checkbox/checkbox.component.html
  tests/test.js
  yarn.lock
Labels: test

#24 refactor(readme): correction des fautes d'orthographe
  README.md
Labels: refactor

#25 Fix(fix-icon): modification de l'icône de l'application
  src/favicon.256x256.png
  src/favicon.512x512.png
  src/favicon.icns
  src/favicon.ico
  src/favicon.png
Labels: fix

#27 Feat(Loader): Ajout du composant Loader
  src/app/app.module.ts
  src/app/components/container/container.component.scss
  src/app/components/loader/loader.component.html
  src/app/components/loader/loader.component.scss
  src/app/components/loader/loader.component.spec.ts
  src/app/components/loader/loader.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.scss
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/variables.scss
Labels: feature

#26 fix(icon-button): raptissage de l'icon-button
  src/app/components/icon-button/icon-button.component.html
  src/app/components/icon-button/icon-button.component.scss
  src/app/components/icon-button/icon-button.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: fix

#28 feat(copybutton): Feature du copy button
  package.json
  src/app/app.module.ts
  src/app/components/copy-button/copy-button.component.html
  src/app/components/copy-button/copy-button.component.scss
  src/app/components/copy-button/copy-button.component.spec.ts
  src/app/components/copy-button/copy-button.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  yarn.lock
Labels: feature

#29 fix(input-number): Correction du max
  src/app/app.module.ts
  src/app/components/input-number/input-number.component.html
  src/app/components/input-number/input-number.component.ts
Labels: fix

#30 refactor(toolbox): ajout copy button à la toolbox
  src/app/components/copy-button/copy-button.component.html
  src/app/components/copy-button/copy-button.component.scss
  src/app/components/copy-button/copy-button.component.ts
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.scss
  src/app/components/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: refactor

#31 refactor(toolbox): ajout d'un bouton setter pour l'input number
  src/app/components/toolbox/toolbox.component.html
  src/app/components/toolbox/toolbox.component.ts
Labels: refactor

#34 feat(button-bar): Préparation de la button bar
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/dropdown/dropdown.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.scss
  src/app/components/home/home.component.ts
  src/app/components/modal/modal.component.scss
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
  src/app/screens/preferences/preferences.component.html
  src/app/screens/preferences/preferences.component.scss
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/preferences/preferences.component.ts
  src/app/screens/toolbox/toolbox.component.html
  src/app/screens/toolbox/toolbox.component.scss
  src/app/screens/toolbox/toolbox.component.spec.ts
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.scss
  src/variables.scss
Labels: feature

#36 maintain(test): ajout des TU et du code coverage
  .gitignore
  .travis.yml
  README.md
  e2e/app.e2e-spec.ts
  e2e/app.po.ts
  e2e/protractor.conf.js
  e2e/tsconfig.e2e.json
  package.json
  src/app/app.component.spec.ts
  src/app/components/button/button.component.spec.ts
  src/app/components/checkbox/checkbox.component.spec.ts
  src/app/components/container/container.component.spec.ts
  src/app/components/copy-button/copy-button.component.spec.ts
  src/app/components/dropdown/dropdown.component.spec.ts
  src/app/components/footer/footer.component.spec.ts
  src/app/components/icon-button/icon-button.component.spec.ts
  src/app/components/input-number/input-number.component.spec.ts
  src/app/components/input/input.component.spec.ts
  src/app/components/loader/loader.component.spec.ts
  src/app/components/modal/modal.component.spec.ts
  src/app/components/modal/modal.component.ts
  src/app/models/MockTranslateLoader.ts
  src/app/models/MockTranslateService.ts
  src/app/models/ServiceResult.ts
  src/app/screens/home/home.component.spec.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/toolbox/toolbox.component.spec.ts
  src/karma.conf.js
  yarn.lock
Labels: maintain

#38 feat(git-service): création du service git
  package.json
  src/app/models/ServiceResult.ts
  src/app/providers/electron.service.ts
  src/app/providers/git.service.ts
  yarn.lock
Labels: feature

#41 fix(dependance): mise à jour d'Electron
  package.json
  yarn.lock
Labels: hotfix

#44 fix(electron-version): changement de version d'electron et electron b…
  package.json
  yarn.lock
Labels: hotfix

#46 refactor(modal): agrandissement de la modal md
  src/app/components/modal/modal.component.scss
  src/app/screens/home/home.component.html
Labels: refactor

#47 maintain(readme): mise à jour du readme
  README.md
  package.json
  yarn.lock
Labels: maintain

#50 refactor(add-modal-loader): Ajout d'un loader à la modal
  src/app/components/modal/modal.component.html
  src/app/components/modal/modal.component.spec.ts
  src/app/components/modal/modal.component.ts
  src/app/screens/toolbox/toolbox.component.html
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: refactor

#51 test(template): réajout d'un template de test
  src/app/components/modal/modal.component.spec.ts
Labels: test

#52 refactor(dropdown): le model de la dropdown est l'id
  src/app/components/dropdown/dropdown.component.html
  src/app/screens/toolbox/toolbox.component.ts
Labels: refactor

#54 refactor(icon-button): ajout option disabled
  src/app/components/icon-button/icon-button.component.html
  src/app/components/icon-button/icon-button.component.scss
  src/app/components/icon-button/icon-button.component.ts
  src/app/screens/toolbox/toolbox.component.html
Labels: refactor

#56 feat(open): Fonctionnalité d'ouverture d'un projet
  package.json
  src/app/app.module.ts
  src/app/providers/electron.service.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.ts
  src/app/screens/toolbox/toolbox.component.scss
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/variables.scss
  yarn.lock
Labels: feature

#55 feat(init): Fonctionnalité d'initialisation d'un projet
  src/app/providers/git.service.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.scss
Labels: feature

#58 feat(info-bar): création d'une barre pour des informations
  src/app/app.module.ts
  src/app/components/info-bar/info-bar.component.html
  src/app/components/info-bar/info-bar.component.scss
  src/app/components/info-bar/info-bar.component.spec.ts
  src/app/components/info-bar/info-bar.component.ts
  src/app/screens/toolbox/toolbox.component.html
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#57 refactor(init): ajoute le nouveau projet aux projets récents
  src/app/providers/git.service.ts
Labels: refactor

#61 feat(left-panel): Développement du panel gauche
  package.json
  src/app/app.module.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.ts
  yarn.lock
Labels: feature

#60 feat(accordion): Ajout du composant accordion
  src/app/app.module.ts
  src/app/components/accordion/accordion.component.html
  src/app/components/accordion/accordion.component.scss
  src/app/components/accordion/accordion.component.spec.ts
  src/app/components/accordion/accordion.component.ts
  src/app/screens/toolbox/toolbox.component.html
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#64 feat(not-opened): Ecran d'accueil et gestion du cas sans repo
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.ts
  src/app/screens/toolbox/toolbox.component.ts
Labels: feature

#59 feat(pref-lang): Gestion du changement de langues
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/providers/language-preferences.service.ts
  src/app/screens/preferences/preferences.component.html
  src/app/screens/preferences/preferences.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#66 refactor(open): gestion mode non ouvert
  package.json
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: refactor

#76 test(tu): ajout correctif pour le git service
  package.json
  src/app/models/MockElectronService.ts
  src/app/models/MockGitService.ts
  src/app/models/MockTranslateLoader.ts
  src/app/screens/home/home.component.spec.ts
Labels: test

#79 test(light-theme): T.Us liés au light theme
  src/app/screens/preferences/preferences.component.spec.ts
Labels: test

#81 test(tu-open): ajout des TU pour open
  src/app/models/MockElectronService.ts
  src/app/models/MockGitService.ts
  src/app/providers/language-preferences.service.ts
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: test

#82 test(tu-init): ajout des TU pour init
  src/app/models/MockElectronService.ts
  src/app/models/MockGitService.ts
  src/app/providers/electron.service.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: test

#80 test(pref-lang): TU des préfences de langue
  src/app/models/MockLanguagePreferenceService.ts
  src/app/models/MockRouter.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/preferences/preferences.component.ts
Labels: test

#83 feat(clone): clone sans le ssh et persistance credential
  README.md
  package.json
  src/app/app.module.ts
  src/app/components/info-bar/info-bar.component.html
  src/app/components/info-bar/info-bar.component.scss
  src/app/components/info-bar/info-bar.component.ts
  src/app/components/input/input.component.html
  src/app/components/input/input.component.ts
  src/app/models/ServiceResult.ts
  src/app/providers/electron.service.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/toolbox/toolbox.component.html
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  yarn.lock
Labels: feature

#85 maintain(general): plusieurs petits changements
  angular.json
  src/app/components/checkbox/checkbox.component.ts
  src/app/components/dropdown/dropdown.component.ts
  src/app/components/info-bar/info-bar.component.spec.ts
  src/app/components/input/input.component.spec.ts
  src/app/components/modal/modal.component.spec.ts
  src/app/models/MockTranslateService.ts
  src/app/screens/home/home.component.scss
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/preferences/preferences.component.ts
  src/app/screens/toolbox/toolbox.component.ts
Labels: maintain

#75 feat(terminal): ajout de la fonctionnalité
  src/app/app.module.ts
  src/app/models/MockElectronService.ts
  src/app/models/MockRouter.ts
  src/app/models/MockTerminalManagerService.ts
  src/app/providers/electron.service.ts
  src/app/providers/terminal-manager.service.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
  src/app/screens/preferences/preferences.component.html
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/preferences/preferences.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  tests/open-terminal.js
Labels: feature

#86 test(tu-clone): ajout des TU pour clone
  src/app/models/MockElectronService.ts
  src/app/models/MockGitService.ts
  src/app/providers/electron.service.ts
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: test

#90 maintain(general): modification version, suppression e2e, léger fix
  .travis.yml
  README.md
  package.json
  src/app/providers/terminal-manager.service.ts
  tests/open-terminal.js
  tests/test.js
Labels: maintain
