Repository GitHarpon/git-harpon, pull requests merged in 2019-04, with the labels that each got.

#170 fix(i18n): correctifs erreur innattention
  src/assets/i18n/fr.json
Labels: fix

#172 Fix file diff
  src/app/components/file-diff-commit/file-diff-commit.component.html
  src/app/components/file-diff-commit/file-diff-commit.component.scss
  src/app/components/file-diff-commit/file-diff-commit.component.spec.ts
  src/app/components/file-diff-commit/file-diff-commit.component.ts
  src/app/components/tree-item/tree-item.component.html
  src/app/components/tree-item/tree-item.component.scss
  src/app/components/tree/tree.component.html
  src/app/components/tree/tree.component.scss
Labels: fix

#171 fix(open): gestion du cas sans commit initial
  src/app/providers/git.service.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: fix

#175 fix(pull-fix): fix du pull
  src/app/providers/git.service.ts
  src/app/screens/home/home.component.html
Labels: fix

#178 feat(doc-1): Première version du DOC1
  angular.json
  package.json
  src/app/app.module.ts
  src/app/components/file-diff-commit/file-diff-commit.component.html
  src/app/components/file-diff-commit/file-diff-commit.component.spec.ts
  src/app/components/file-diff-commit/file-diff-commit.component.ts
  src/app/components/monaco-wrapper/monaco-editor-wrapper.component.html
  src/app/components/monaco-wrapper/monaco-editor-wrapper.component.scss
  src/app/components/monaco-wrapper/monaco-editor-wrapper.component.ts
  src/app/components/tree-item/tree-item.component.html
  src/app/components/tree-item/tree-item.component.spec.ts
  src/app/components/tree-item/tree-item.component.ts
  src/app/components/tree/tree.component.html
  src/app/components/tree/tree.component.spec.ts
  src/app/components/tree/tree.component.ts
  src/app/models/DiffFileInformation.ts
  src/app/models/MockGitService.ts
  src/app/models/MockRightPanelService.ts
  src/app/providers/git.service.ts
  src/app/providers/right-panel.service.ts
  src/app/screens/diff-view/diff-view.component.html
  src/app/screens/diff-view/diff-view.component.scss
  src/app/screens/diff-view/diff-view.component.spec.ts
  src/app/screens/diff-view/diff-view.component.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-branch.component.spec.ts
  src/app/screens/home/home-checkout.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home-pull.component.spec.ts
  src/app/screens/home/home-push.component.spec.ts
  src/app/screens/home/home-rename.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/right-panel/right-panel.component.spec.ts
  src/app/screens/send-commit/send-commit.component.html
  src/app/screens/send-commit/send-commit.component.spec.ts
  src/app/screens/send-commit/send-commit.component.ts
  src/app/screens/toolbox/toolbox.component.spec.ts
  src/app/screens/view-commit/view-commit.component.html
  src/app/screens/view-commit/view-commit.component.spec.ts
  src/app/screens/view-commit/view-commit.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/styles.scss
  yarn.lock
Labels: feature, test

#176 feat(graph-view): première version du rendu du graphe
  package.json
  src/app/models/MockGraphService.ts
  src/app/providers/git.service.ts
  src/app/providers/graph.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home.component.ts
  yarn.lock
Labels: feature, test

#179 release(change-version): passage en 1.3.0
  package.json
Labels: refactor

#177 feat(BRANCH-4): ajout de la fonctionnalité "Fusion de deux branches"
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/providers/graph.service.ts
  src/app/screens/home/home-branch.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.html
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#182 fix(branch-7): erreur de regression fixée
  src/app/screens/home/home.component.html
Labels: fix

#183 release(v4): Déploiement client
  src/app/screens/home/home.component.html
Labels: release

#187 refactor(doc-1): dark css pour le doc-1
  package.json
  src/app/screens/diff-view/diff-view.component.html
  src/app/screens/diff-view/diff-view.component.scss
  src/app/screens/diff-view/diff-view.component.ts
  src/styles.scss
Labels: feature

#189 feat(branch-6): Ajout fonctionnalité rebase
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-rebase.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.html
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#190 fix(terminal): Correction des bug pour les terminaux sous windows
  src/app/providers/terminal-manager.service.ts
Labels: fix

#188 fix(COMMIT-3): suite de corrections pour l'envoie de commit
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: fix

#191 fix(button-bar): ajout d'un placeHolder dans la barre de recherche
  src/app/screens/home/home.component.html
Labels: fix

#192 fix(loader): fix de l'opacité du fond du loader en light-theme
  src/app/components/loader/loader.component.scss
Labels: fix

#194 feat(graph-view): Partie finale du graphe
  angular.json
  src/app/models/MockGitService.ts
  src/app/models/MockGraphService.ts
  src/app/providers/git.service.ts
  src/app/providers/graph.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.scss
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home.component.ts
  src/assets/js/draw.js
  src/assets/js/gitgraph.js
  src/index.html
  src/styles.scss
Labels: feature

#195 release(v5): Livraison finale des fonctionnalités
  angular.json
  package.json
  src/app/components/loader/loader.component.scss
  src/app/models/MockGitService.ts
  src/app/models/MockGraphService.ts
  src/app/providers/git.service.ts
  src/app/providers/graph.service.ts
  src/app/providers/terminal-manager.service.ts
  src/app/screens/diff-view/diff-view.component.html
  src/app/screens/diff-view/diff-view.component.scss
  src/app/screens/diff-view/diff-view.component.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.scss
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-rebase.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.html
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/assets/js/draw.js
  src/assets/js/gitgraph.js
  src/index.html
  src/styles.scss
Labels: release
