Repository GitHarpon/git-harpon, pull requests merged in 2019-03, with the labels that each got.

#91 maintain(general): cache travis, fix "error" translate et réajout TU composants
  .travis.yml
  angular.json
  src/app/components/input/input.component.spec.ts
  src/app/components/modal/modal.component.spec.ts
  src/app/screens/home/home.component.spec.ts
  src/app/screens/home/home.component.ts
  src/assets/i18n/fr.json
Labels: maintain, test

#92 test(tu-footer): Ajout des tests unitaires pour le footer
  src/app/components/footer/footer.component.spec.ts
  src/app/components/footer/footer.component.ts
  src/app/models/MockElectronService.ts
  src/app/providers/electron.service.ts
Labels: test

#93 test(tu-container): Suppression d'une méthode inutile
  src/app/components/container/container.component.ts
Labels: test

#94 TUs pour les dropdowns
  src/app/components/dropdown/dropdown.component.spec.ts
  src/app/components/dropdown/dropdown.component.ts
Labels: test

#96 maintain(tu): séparation tu home en plusieurs fichiers
  angular.json
  src/app/components/dropdown/dropdown.component.spec.ts
  src/app/components/footer/footer.component.spec.ts
  src/app/components/input/input.component.spec.ts
  src/app/components/modal/modal.component.spec.ts
  src/app/models/MockAlternativeElectronService.ts
  src/app/models/MockElectronService.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home.component.spec.ts
  src/app/screens/preferences/preferences.component.spec.ts
Labels: maintain, test

#97 test(accordion): Tests du composant accordion
  src/app/components/accordion/accordion.component.spec.ts
  src/app/components/accordion/accordion.component.ts
Labels: test

#98 test(loader): Ajout tests du composant loader
  src/app/components/loader/loader.component.spec.ts
  src/app/components/loader/loader.component.ts
Labels: test

#95 test(tu-copy-button): TU pour les copy button
  src/app/components/copy-button/copy-button.component.spec.ts
  src/app/components/copy-button/copy-button.component.ts
Labels: test

#101 test(input-number): ajout des TU pour l'input-number
  src/app/components/input-number/input-number.component.html
  src/app/components/input-number/input-number.component.spec.ts
Labels: test

#100 test(checkbox): ajout des TU pour la checkbox
  src/app/components/checkbox/checkbox.component.spec.ts
  src/app/components/checkbox/checkbox.component.ts
Labels: test

#99 test(button): ajout des TU pour le button
  src/app/components/button/button.component.spec.ts
  src/app/components/button/button.component.ts
Labels: test

#105 test(modal): Tests sur le composant modal
  src/app/components/modal/modal.component.spec.ts
  src/app/components/modal/modal.component.ts
Labels: test

#103 fix(clone): reset password après erreur
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
Labels: fix

#104 feat(home-panels): Ajout des panels lorsqu'un projet est ouvert
  src/app/app.module.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.scss
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.html
  src/app/screens/left-panel/left-panel.component.scss
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/right-panel/right-panel.component.html
  src/app/screens/right-panel/right-panel.component.scss
  src/app/screens/right-panel/right-panel.component.spec.ts
  src/app/screens/right-panel/right-panel.component.ts
Labels: feature

#107 test(icon-button): ajout des tests unitaires
  src/app/components/icon-button/icon-button.component.spec.ts
  src/app/components/icon-button/icon-button.component.ts
  yarn.lock
Labels: test

#106 test(info-bar): ajout des tests unitaires
  src/app/components/info-bar/info-bar.component.spec.ts
  src/app/components/info-bar/info-bar.component.ts
Labels: test

#108 test(toolbox): ajout des TU
  src/app/components/footer/footer.component.ts
  src/app/models/MockElectronService.ts
  src/app/providers/electron.service.ts
  src/app/screens/toolbox/toolbox.component.spec.ts
  src/app/screens/toolbox/toolbox.component.ts
Labels: test

#110 fix(home-panels): ajout d'un léger correctif css
  src/app/screens/graph/graph.component.scss
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/left-panel/left-panel.component.scss
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/right-panel/right-panel.component.scss
  src/app/screens/right-panel/right-panel.component.spec.ts
Labels: fix

#111 refactor(home): mise à dispo du changement de vue depuis home + tu
  src/app/app.module.ts
  src/app/models/MockRightPanelService.ts
  src/app/providers/right-panel.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/right-panel/right-panel.component.html
  src/app/screens/right-panel/right-panel.component.scss
  src/app/screens/right-panel/right-panel.component.spec.ts
  src/app/screens/right-panel/right-panel.component.ts
  src/app/screens/send-commit/send-commit.component.html
  src/app/screens/send-commit/send-commit.component.scss
  src/app/screens/send-commit/send-commit.component.spec.ts
  src/app/screens/send-commit/send-commit.component.ts
  src/app/screens/view-commit/view-commit.component.html
  src/app/screens/view-commit/view-commit.component.scss
  src/app/screens/view-commit/view-commit.component.spec.ts
  src/app/screens/view-commit/view-commit.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: refactor

#112 feat(pre-branch): préparation de la gestion de branches
  src/app/app.module.ts
  src/app/components/accordion/accordion.component.html
  src/app/components/accordion/accordion.component.scss
  src/app/models/MockGitService.ts
  src/app/models/MockLeftPanelService.ts
  src/app/providers/git.service.ts
  src/app/providers/left-panel.service.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.html
  src/app/screens/left-panel/left-panel.component.scss
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/app/screens/toolbox/toolbox.component.html
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#117 fix(tu): gestion setTimeout
  src/app/components/copy-button/copy-button.component.spec.ts
  src/app/components/copy-button/copy-button.component.ts
Labels: fix, test

#124 fix(textarea): fix width
  src/app/components/commit-text-area/commit-text-area.component.scss
  src/app/components/text-area/text-area.component.scss
  src/app/screens/toolbox/toolbox.component.html
Labels: fix

#120 Feat(Pull-rebase): Ajout de la fonctionnalité
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-pull.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature, test

#129 fix(init): création d'un commit à l'initialisation
  src/app/providers/git.service.ts
Labels: fix

#130 fix(BRANCH-1): Apport d'un correctif pour le left panel
  src/app/models/MockLeftPanelService.ts
  src/app/providers/left-panel.service.ts
  src/app/screens/home/home-checkout.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
Labels: fix

#127 feat(COMMIT-1): Ajout de la fonctionnalité de Stage et Unstage
  src/app/app.module.ts
  src/app/components/file-diff-commit/file-diff-commit.component.html
  src/app/components/file-diff-commit/file-diff-commit.component.scss
  src/app/components/file-diff-commit/file-diff-commit.component.spec.ts
  src/app/components/file-diff-commit/file-diff-commit.component.ts
  src/app/models/MockGitService.ts
  src/app/models/MockRightPanelService.ts
  src/app/providers/git.service.ts
  src/app/providers/right-panel.service.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-checkout.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home-pull.component.spec.ts
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/preferences/preferences.component.spec.ts
  src/app/screens/right-panel/right-panel.component.spec.ts
  src/app/screens/send-commit/send-commit.component.html
  src/app/screens/send-commit/send-commit.component.scss
  src/app/screens/send-commit/send-commit.component.spec.ts
  src/app/screens/send-commit/send-commit.component.ts
  src/app/screens/toolbox/toolbox.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature, test

#132 fix(branch): correction changement de projet
  src/app/screens/home/home.component.html
Labels: fix

#136 feat(graph-1-raw): création d'une première version du graphe
  src/app/app.module.ts
  src/app/components/container/container.component.scss
  src/app/models/MockGraphService.ts
  src/app/providers/git.service.ts
  src/app/providers/graph.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.scss
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home-alternative.component.spec.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home-checkout.component.spec.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-init.component.spec.ts
  src/app/screens/home/home-open.component.spec.ts
  src/app/screens/home/home-pull.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: feature

#138 feat(commit-4): visualisation d'un commit
  package.json
  src/app/components/commit-text-area/commit-text-area.component.html
  src/app/components/copy-button/copy-button.component.scss
  src/app/components/file-diff-commit/file-diff-commit.component.scss
  src/app/components/text-area/text-area.component.spec.ts
  src/app/models/CommitInformations.ts
  src/app/models/MockGitService.ts
  src/app/models/MockRightPanelService.ts
  src/app/providers/git.service.ts
  src/app/providers/right-panel.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/app/screens/right-panel/right-panel.component.spec.ts
  src/app/screens/right-panel/right-panel.component.ts
  src/app/screens/send-commit/send-commit.component.spec.ts
  src/app/screens/view-commit/view-commit.component.html
  src/app/screens/view-commit/view-commit.component.scss
  src/app/screens/view-commit/view-commit.component.spec.ts
  src/app/screens/view-commit/view-commit.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  yarn.lock
Labels: feature, test

#139 test(coverage): coverage 100% sur graphe + petit fix branche
  src/app/providers/git.service.ts
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
Labels: fix, test

#140 refactor(branch-7): changement de nom d'une variable conflictueuse
  src/app/screens/home/home-rename.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
Labels: refactor

#141 feat(sync-2): ajout de la fonctionnalité pull-rebase
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-pull.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  yarn.lock
Labels: feature

#142 feat(push): fonctionnalité du push
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-clone.component.spec.ts
  src/app/screens/home/home-push.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: feature

#145 fix(release): Fix de la release
  main.ts
  src/app/components/commit-text-area/commit-text-area.component.html
  src/app/screens/toolbox/toolbox.component.html
Labels: fix

#147 fix(release): correction pour changement de branche
  src/app/providers/git.service.ts
  src/app/screens/home/home.component.ts
Labels: fix

#148 fix(branch-2): correctif pour la création de branche en release
  src/app/providers/git.service.ts
Labels: fix

#152 fix(sync-2): fix du pull rebase
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-pull.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
Labels: fix

#151 fix(sync-1): fix du push
  src/app/providers/git.service.ts
  src/app/screens/home/home-push.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: fix

#154 refactor(preferences): retrait de l'onglet obsolète
  src/app/screens/preferences/preferences.component.html
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: refactor

#150 fix(branch-3): Résolution des problèmes de la fonctionnalité
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/home/home-branch.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/left-panel/left-panel.component.html
  src/app/screens/left-panel/left-panel.component.spec.ts
  src/app/screens/left-panel/left-panel.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: fix

#165 fix(no-commit-found): fix suite aux retours clients
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/home/home-base.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
  src/app/screens/view-commit/view-commit.component.spec.ts
  src/app/screens/view-commit/view-commit.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
Labels: fix

#167 feat(COMMIT-3): ajout de la fonctionnalité de commit
  src/app/components/button/button.component.html
  src/app/components/button/button.component.scss
  src/app/components/button/button.component.ts
  src/app/models/MockGitService.ts
  src/app/providers/git.service.ts
  src/app/screens/graph/graph.component.html
  src/app/screens/graph/graph.component.spec.ts
  src/app/screens/graph/graph.component.ts
  src/app/screens/send-commit/send-commit.component.html
  src/app/screens/send-commit/send-commit.component.scss
  src/app/screens/send-commit/send-commit.component.spec.ts
  src/app/screens/send-commit/send-commit.component.ts
  src/app/screens/toolbox/toolbox.component.ts
  src/app/screens/view-commit/view-commit.component.html
  src/app/screens/view-commit/view-commit.component.scss
  src/app/screens/view-commit/view-commit.component.spec.ts
  src/app/screens/view-commit/view-commit.component.ts
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/variables.scss
Labels: feature

#166 fix(branch-7): retours utilisateur, nom par défaut dans renamebar, tests
  src/app/providers/git.service.ts
  src/app/screens/home/home-rename.component.spec.ts
  src/app/screens/home/home.component.html
  src/app/screens/home/home.component.ts
Labels: enhancement, fix

#169 fix(branch-7): erreur de console fixée
  src/app/providers/git.service.ts
  src/app/screens/home/home-rename.component.spec.ts
  src/app/screens/home/home.component.ts
Labels: fix
